apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-applier-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kube-applier-operator
  template:
    metadata:
      labels:
        name: kube-applier-operator
    spec:
      serviceAccountName: kube-applier-operator
      containers:
        - name: kube-applier-operator
          # Replace this with the built image name
          image: quay.io/bigkevmcd/k8s-applier
          command:
          - kube-applier-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "kube-applier-operator"
