kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-applier
subjects:
- kind: ServiceAccount
  name: k8s-applier
roleRef:
  kind: Role
  name: k8s-applier
  apiGroup: rbac.authorization.k8s.io
